version: 2
project_name: ganache

builds:
  - id: ganache
    main: ./cmd/ganache
    binary: ganache
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: migrate
    main: ./cmd/migrate
    binary: ganache-migrate
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    builds:
      - ganache
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
    wrap_in_directory: true

  - id: migrate
    builds:
      - migrate
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-migrate_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
    wrap_in_directory: true

checksum:
  name_template: "checksums.txt"

sboms:
  - id: archive
    artifacts: archive

signs:
  - id: cosign-checksums
    cmd: cosign
    artifacts: checksum
    signature: "${artifact}.sig"
    args:
      - sign-blob
      - "--yes"
      - "--key=${COSIGN_KEY}"
      - "--output-signature=${signature}"
      - "${artifact}"

changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^chore:'
